# coding=utf-8
import random
import time
import turtle
t = turtle.Turtle()
for i in range(10, 0, -1):
    a = random.random()
    b = random.random()
    c = random.random()
    t.color(a, b, c)
    t.write(i, align="center", font=("", 200, ""))
    time.sleep(1)
    t.clear()
t.reset()
t.speed(0)
c = ["cyan", "blue", "orange", "yellow", "red", "white"]
r = 120
for i in c:
    t.color(i)
    t.begin_fill()
    t.circle(r)
    t.end_fill()
    r -= 15
t.reset()
turtle.bgcolor("black")
for i in range(100):
    a = random.random()
    b = random.random()
    c = random.random()
    t.color(a, b, c)
    t.dot(100)
t.reset()
turtle.bgcolor("white")
t.width(5)
t.showturtle()
t.penup()
t.goto(0, -200)
t.pd()
t.fillcolor("black")
t.speed(0)
t.begin_fill()
t.circle(100, 180)
t.circle(-100, 180)
t.circle(-200, -180)
t.end_fill()
t.circle(-200, -180)
t.setheading(-90)
t.penup()
t.forward(100)
t.dot(50, "black")
t.forward(200)
t.dot(50, "white")
t.pd()
t.hideturtle()
t.reset()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(30)
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)
t.forward(100)
t.forward(100)
t.left(650)
t.forward(100)
t.forward(50)
t.left(40)
t.forward(100)
t.reset()
t.write("THE END", align="center", font=("Microsoft YaHei", 100, ""))
turtle.done()
